# 1 Data Types
Zoals besproken zijn er verschillende meetniveaus van data, te weten: 
* Nominaal, 
* Ordinaal, 
* Interval en 
* Ratio

Hierbij gaat het om het type data en wat je met deze data kunt. Dit lijkt niet belangrijk, maar kan je al een heleboel vertellen over de data zelf. Om gemakkelijk met de data te kunnen werken, moet de computer weten om wat voor data het gaat. Daarom zijn er verschillende *data types*. 

Over het algemeen onderscheiden we de volgende data types: 
* Integer (Gehele getallen)
* Float (Kommagetallen)
* Char (letter of teken)
* String (reeks van chars)
* Boolean (ja of nee, waar of niet waar)
* Date (Datum)
* Time (Tijd)
* Datetime (Datum, tijd en eventueel tijdzone)

Om te zien wat de data types doen, gebruiken we Python. Hier kunnen we zien wat er gebreurd wanneer data types in een bepaalde vorm zijn opgeslagen en hoe deze dan nog gebruikt kunnen worden.

## 1.1 Numerieke waarden
Onder de numerieke waarden hebben we 2 data types, de integers en de floats. De eerste slaat gehele getallen op, en de tweede gehele getallen en kommagetallen. Afhankelijk van je data maak je een keuze. Dit heeft vooral met de opslag ruimte te maken. Een kommagetal vraag meer geheugen dan een geheel getal. 

Laten we kijken wat we kunnen met deze data types en hoe zij zich gedragen.

In [ ]:
# Eerst slaan we waarden op in de variablen 'x' en 'y'
x = 10    # int
y = 3.8  # float

# Vervolgens laten we dit weergeven op het scherm met een 'print'
print(x)
print(y)

In [ ]:
# Met deze getallen kunnen we berekeningen doen. Kun jij van te voren bedenken wat de uitkomst is? 
print(x + y)
print(x - y)
print(x * y)

Zie je wat er is gebeurd? De getallen uitkomsten zijn nu allemaal floats geworden. We kunnen ook afdwingen dat we alleen gehele getallen willen.

In [ ]:
# We vertellen nu expliciet dat we gehele getallen als uitkomst willen
print(int(x + y))
print(int(x - y))
print(int(x * y))

In [ ]:
# En zo kunnen we ook expliciet om een float vragen
print(float(x + x))

Dat ging best makkelijk toch? Laten we nu kijken naar het werken met karakters. 

## 1.2 Char en String
Char en String zijn andere data typen dan de int en float die we eerder hebben gezien. Deze kunnen 1 (char) of meerdere (string) tekens opslaan. Dit kunnen getallen, letters en tekens zijn. 

Laten we kijken wat we met de chars en strings kunnen.

In [ ]:
# Eerst slaan we waarden op in de variablen 'x' en 'y'
s = 'Hello World'   # string
c = 'W'             # char

# Vervolgens laten we dit weergeven op het scherm met een 'print'
print(s)
print(c)

In [ ]:
# Laten we kijken of we ook met deze waarden kunnen 'rekenen'. Kun jij van te voren bedenken wat de uitkomst is? 
print(s + c)
print(s - c)

He dat is leuk, we kunnen strings en chars bij elkaar samenvoegen. Een letterweghalen gaat op een andere manier.  Laten we dat ook bekijken.

In [ ]:
# Selecteren van een letter in een string
print(s[0])   # Geeft het eerste karakter, ja Python begint met tellen vanaf 0. 
print(s[6])

# Een letter aan de voor of achterkant weghalen
print(s[1:])
print(s[:-1])

# En letter kunnen we vervangen door een andere letter of door niets
print(s.replace('o', 'Q'))
print(s.replace('o', ''))

In [ ]:
# Tot slot kunnen we ook getallen als een karakter opslaan. 
z = '10'

# Kun jij bedenken wat de uitkomst is van het volgende?
print(s + z)
print(x + z)

Nu we hebben gezien hoe we met numerieke waarden en met karakters om kunnen gaan, gaan we kijken hoe dat samenkomt met een boolean. 

## 1.3 Boolean
Als eerste de boolean. Dit is een binaire opslagvorm en geeft alleen waar of niet waar aan. Dit kan met 'True'en 'False' of met '1' en '0'. Laten we kijken wat we hiermee kunnen.

In [ ]:
# Eerst slaan we waarden op in de variablen 'x' en 'y'
t = True
f = False
# Vervolgens printen we de variabelen
print(t)
print(f)

In [ ]:
# Kunnen we de variablen bij elkaar optellen?
print(t + f)

Had je deze outkomst verwacht?

In [ ]:
# Kunnen we andere sommen toepassen?
print(t * f)
print(t - f)

In [ ]:
# Dit wordt vaak gebruikt voor het bepalen wat er moet gebeuren
print(x)
print(y)

if x > y:
  print("x is greater than y")
else:
  print("x is smaller than y")

## 1.4 Datetime
De laatste voor de basis types is de datum en tijd. Dit type heeft in totaal 3 vormen, alleen een datum, alleen een tijd of een datum en tijd en eventueel ook een tijdzone. 

Laten we kijken wat we hiermee kunnen. 

Dit data type zit niet standaard in python dus moeten we vertellen dat we met dit type willen werken. Dit doen we door een datum tijd package te gebruiken.

In [ ]:
# Import datum tijd package
import datetime

# De datum en tijd van vandaag opslaan in een variable
d = datetime.datetime.now()

# Vervolgens printen we de variabelen
print(d)

In [ ]:
# We kunnen ook een eigen datum maken
d2 = datetime.datetime(2021, 1, 31)   # Format is year, month, date

print(d2)

In [ ]:
# En er zijn een aantal handige standaard functies
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%A"))
print(d.strftime("%B"))